-- Inserir dados para o estado do Acre
INSERT INTO Estado (sigla, nome) VALUES ('AC', 'Acre');
INSERT INTO Estado (sigla, nome) VALUES ('AL', 'Alagoas');
INSERT INTO Estado (sigla, nome) VALUES ('AM', 'Amazonas');
INSERT INTO Estado (sigla, nome) VALUES ('AP', 'Amapá');
INSERT INTO Estado (sigla, nome) VALUES ('BA', 'Bahia');
INSERT INTO Estado (sigla, nome) VALUES ('CE', 'Ceará');
INSERT INTO Estado (sigla, nome) VALUES ('DF', 'Distrito Federal');
INSERT INTO Estado (sigla, nome) VALUES ('ES', 'Espírito Santo');
INSERT INTO Estado (sigla, nome) VALUES ('GO', 'Goiás');
INSERT INTO Estado (sigla, nome) VALUES ('MA', 'Maranhão');
INSERT INTO Estado (sigla, nome) VALUES ('MG', 'Minas Gerais');
INSERT INTO Estado (sigla, nome) VALUES ('MT', 'Mato Grosso');
INSERT INTO Estado (sigla, nome) VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO Estado (sigla, nome) VALUES ('PA', 'Pará');
INSERT INTO Estado (sigla, nome) VALUES ('PB', 'Paraíba');
INSERT INTO Estado (sigla, nome) VALUES ('PR', 'Paraná');
INSERT INTO Estado (sigla, nome) VALUES ('PE', 'Pernambuco');
INSERT INTO Estado (sigla, nome) VALUES ('PI', 'Piauí');
INSERT INTO Estado (sigla, nome) VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO Estado (sigla, nome) VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO Estado (sigla, nome) VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO Estado (sigla, nome) VALUES ('RO', 'Rondônia');
INSERT INTO Estado (sigla, nome) VALUES ('RR', 'Roraima');
INSERT INTO Estado (sigla, nome) VALUES ('SC', 'Santa Catarina');
INSERT INTO Estado (sigla, nome) VALUES ('SE', 'Sergipe');
INSERT INTO Estado (sigla, nome) VALUES ('SP', 'São Paulo');
INSERT INTO Estado (sigla, nome) VALUES ('TO', 'Tocantins');
